// The synonym table behind search_components and find_tokens (DESIGN.md §6: "Synonym table.
// Zero results return the nearest five names, never the catalog"). Keys are what people and
// design tools call things; values are tenet-ui component ids or token groups.

export const COMPONENT_SYNONYMS: Record<string, string[]> = {
  dropdown: ['select', 'menu'],
  combobox: ['select'],
  picker: ['select', 'date-picker'],
  modal: ['dialog'],
  overlay: ['dialog', 'popover'],
  drawer: ['dialog'],
  sheet: ['dialog'],
  chip: ['tag'],
  pill: ['tag', 'badge'],
  status: ['tag', 'badge', 'banner'],
  count: ['badge'],
  toggle: ['switch', 'segmented-control'],
  checkbox: ['checkbox'],
  radio: ['radio-group'],
  notification: ['toast', 'banner'],
  snackbar: ['toast'],
  alert: ['banner', 'dialog'],
  callout: ['banner'],
  message: ['banner', 'toast'],
  loading: ['spinner', 'skeleton', 'progress-bar'],
  loader: ['spinner', 'skeleton'],
  placeholder: ['skeleton', 'empty-state'],
  progress: ['progress-bar'],
  input: ['text-input', 'textarea', 'number-input'],
  textbox: ['text-input'],
  field: ['text-input', 'form-control'],
  search: ['text-input'],
  form: ['form-control'],
  label: ['form-control', 'tag'],
  caption: ['form-control', 'text'],
  helper: ['form-control'],
  validation: ['form-control'],
  error: ['form-control', 'banner'],
  table: ['table', 'data-table'],
  grid: ['grid', 'data-table', 'table'],
  list: ['table', 'stack', 'menu'],
  row: ['table', 'stack'],
  columns: ['grid'],
  layout: ['grid', 'stack'],
  container: ['card', 'stack'],
  panel: ['card'],
  section: ['card', 'stack'],
  tile: ['card'],
  box: ['card', 'stack'],
  hero: ['empty-state', 'heading'],
  empty: ['empty-state'],
  'no results': ['empty-state'],
  'zero state': ['empty-state'],
  title: ['heading'],
  header: ['heading', 'table'],
  h1: ['heading'],
  h2: ['heading'],
  paragraph: ['text'],
  body: ['text'],
  copy: ['text'],
  typography: ['heading', 'text'],
  link: ['link'],
  anchor: ['link'],
  button: ['button', 'icon-button'],
  cta: ['button'],
  action: ['button', 'icon-button', 'menu'],
  icon: ['icon', 'icon-button'],
  glyph: ['icon'],
  avatar: ['avatar'],
  profile: ['avatar'],
  tooltip: ['tooltip'],
  hint: ['tooltip', 'form-control'],
  popover: ['popover'],
  popup: ['popover', 'menu', 'dialog'],
  tabs: ['tabs', 'segmented-control'],
  tab: ['tabs'],
  navigation: ['tabs', 'breadcrumbs', 'link'],
  nav: ['tabs', 'breadcrumbs'],
  breadcrumb: ['breadcrumbs'],
  pagination: ['pagination'],
  pager: ['pagination'],
  accordion: ['accordion'],
  collapsible: ['accordion'],
  disclosure: ['accordion'],
  expander: ['accordion'],
  divider: ['divider'],
  separator: ['divider'],
  rule: ['divider'],
  calendar: ['calendar', 'date-picker'],
  date: ['date-picker', 'calendar'],
  number: ['number-input'],
  stepper: ['number-input', 'pagination'],
  counter: ['number-input', 'badge'],
  textarea: ['textarea'],
  'multi-line': ['textarea'],
  'segmented control': ['segmented-control'],
  'button group': ['segmented-control'],
  'toggle group': ['segmented-control'],
  stack: ['stack'],
  flex: ['stack'],
  spacing: ['stack', 'grid'],
  toast: ['toast'],
  banner: ['banner'],
  spinner: ['spinner'],
  skeleton: ['skeleton'],
  card: ['card'],
  dialog: ['dialog'],
  menu: ['menu'],
  select: ['select'],
  switch: ['switch'],
  tag: ['tag'],
  badge: ['badge'],
};

/** What people call token groups. */
export const TOKEN_GROUP_SYNONYMS: Record<string, string[]> = {
  spacing: ['space'],
  space: ['space'],
  gap: ['space'],
  padding: ['space'],
  margin: ['space'],
  inset: ['space'],
  radius: ['borderRadius'],
  rounded: ['borderRadius'],
  corner: ['borderRadius'],
  'border radius': ['borderRadius'],
  border: ['borderColor', 'borderWidth'],
  stroke: ['borderWidth', 'borderColor'],
  outline: ['borderColor'],
  color: ['fgColor', 'bgColor', 'borderColor'],
  colour: ['fgColor', 'bgColor', 'borderColor'],
  text: ['fgColor', 'fontSize', 'fontFamily'],
  foreground: ['fgColor'],
  'text color': ['fgColor'],
  ink: ['fgColor'],
  background: ['bgColor'],
  surface: ['bgColor'],
  fill: ['bgColor'],
  canvas: ['bgColor'],
  font: ['fontFamily', 'fontSize', 'fontWeight'],
  typeface: ['fontFamily'],
  family: ['fontFamily'],
  size: ['fontSize', 'control'],
  'font size': ['fontSize'],
  scale: ['fontSize', 'space'],
  weight: ['fontWeight'],
  bold: ['fontWeight'],
  'line height': ['lineHeight'],
  leading: ['lineHeight'],
  'letter spacing': ['letterSpacing'],
  tracking: ['letterSpacing'],
  shadow: ['shadow'],
  elevation: ['shadow'],
  depth: ['shadow'],
  breakpoint: ['breakpoint'],
  responsive: ['breakpoint'],
  viewport: ['breakpoint'],
  control: ['control'],
  height: ['control'],
  accent: ['fgColor', 'bgColor', 'borderColor'],
  brand: ['fgColor', 'bgColor'],
  primary: ['bgColor', 'fgColor'],
  danger: ['fgColor', 'bgColor', 'borderColor'],
  success: ['fgColor', 'bgColor', 'borderColor'],
  attention: ['fgColor', 'bgColor', 'borderColor'],
  warning: ['fgColor', 'bgColor', 'borderColor'],
  muted: ['fgColor', 'bgColor'],
  disabled: ['fgColor', 'bgColor'],
};

/** Simple trigram similarity for "did you mean" candidates. */
export function similarity(a: string, b: string): number {
  const grams = (s: string): Set<string> => {
    const t = `  ${s.toLowerCase()} `;
    const out = new Set<string>();
    for (let i = 0; i < t.length - 2; i++) out.add(t.slice(i, i + 3));
    return out;
  };
  const ga = grams(a);
  const gb = grams(b);
  let hit = 0;
  for (const g of ga) if (gb.has(g)) hit++;
  return ga.size + gb.size === 0 ? 0 : (2 * hit) / (ga.size + gb.size);
}

export function tokenize(q: string): string[] {
  return q.toLowerCase().replace(/[^a-z0-9\s-]/g, ' ').split(/[\s-]+/).filter((w) => w.length > 1);
}
